name: Run short e2e tests

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled, unlabeled]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setupGo
        uses: actions/setup-go@v5
        with:
          go-version: "=1.22.0"
      - name: Run e2e tests
        run: ISOLATED_MODE=true  USE_EKS=false GINKGO_LABEL_FILTER=short make test-e2e
      - name: Collect run artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: _artifacts
